### ISSUE TITLE
Removed JQuery, Added Webpack Configuration 

### ISSUE THREAD

**Issue by Prottoy2938** [Christian-von-Uffel/Perfecting-Product#1]
> **https://github.com/Prottoy2938/Perfecting-Product**

Implemented the same project in vanilla `JavaScript` without using `JQuery`.

Added `webpack` to enable code splitting and better development feature. It would also help to extend this web application in the future without any hassle and could also use **_npm packages_**

This new version has a lower page size than the previous one, more details [here](https://gtmetrix.com/compare/k5ljV4ap/dDJtLRkf)

View the application live here: https://prottoy2938.github.io/Perfecting-Product/

**Comment by Prottoy2938** [comment]
Since the new codebase is drastically different from the main one, GitHub doesn't allow to create a pull request, hence this asking via issue

**Comment by Christian-von-Uffel** [comment]
Stopped using jQuery or fade in animations entirely. May revisit later
